### ISSUE TITLE
Confusing start and stop message

### ISSUE THREAD

**Issue by jubiman** [Mass1milian0/devious-messagger#17]
## Issue
Currently, when a Minecraft server connects to the chat, or when it disconnects, it sends the `Server is starting/stopping` message. This message is confusing (at least to me), as I will think the Minecraft server is restarting (so I won't be able to join until it's back on), and not just the chat server that will be down.

## Proposed fix
Change the message to specify the chat server like `Chat server starting/stopping`, or more specifically because it sends the message when it connects with a Minecraft server, something like `[SERVER] Chat connection established/lost`

**Comment by Mass1milian0** [comment]
yes, the message is misleading, but only to a certain point, thing is, the only way for me to know if a server has started or stopped is by making an assumption on the websocket connection

the mod only connects to the server after minecraft is done loading, so while misleading it's a good indicator on wheater a server is joinable or not, issue here is that when a discconection happens (because i turn off the websocket server, or something else happens) and reconnects the message server is starting is sent out

while the proposed fix would be acceptable, another way would be to have a dedicated event which is sent out when the server is starting or stopping, however, that would require the websocket client to connect to the server in the loading stage (and on the unloading stage)

i think the proposed fix is simplier, as it only requires me to change a string, but the other way ensures a proper server status report
